title: Rebick-Blog
description: "Portafolio"
iconURL: assets/scam.png
author:
  name: "ImIN"
  email: "gorosergio17+rebickme@gmail.com"
  url: "rebick.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "xREBICKx"
year : "2023"
google_analytics: G-WEVJ71K264
